version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: fiap
      POSTGRES_PASSWORD: fiap
      POSTGRES_DB: fiap-database
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
   

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://fiap:fiap@db:5432/fiap-database
    volumes:
      - ./:/app  